### ISSUE TITLE
Add topic tags

### ISSUE THREAD

**Issue by Beliavsky** [lollocava00/1-D-Supernova-shock-radius-evolution#2]
I suggest adding the topics `supernova`, `astrophysics`, in the About section, as explained at https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics

**Comment by lollocava00** [comment]
yea that is a good idea. I'm quite new to github thanks for the great advice, let me know if there is anything else i should do.
